### ISSUE TITLE
Feature request: Alerts

### ISSUE THREAD

**Issue by salvdev** [shakrmedia/petal#7]
Any chance on getting an Alert component similar to bootstrap 4's alerts? [https://v4-alpha.getbootstrap.com/components/alerts/](https://v4-alpha.getbootstrap.com/components/alerts/)

**Comment by zvuc** [comment]
Great idea! There is already a similar component we use internally in Shakr, so it won't be too hard to bring it to Petal as well. I'll look into this again later when I have some spare time :)

**Comment by zvuc** [comment]
Feature has been added with [0.7.0 release](https://github.com/shakrmedia/petal/releases/tag/0.7.0).
